feat:test

diff --git a/.github/workflows/upload.yml b/.github/workflows/upload.yml
--- a/.github/workflows/upload.yml
+++ b/.github/workflows/upload.yml
@@ -201,7 +201,6 @@ jobs:
           exit 1
           }
 
-          nvm -v
           nvm use --lts
 
           cd  /var/www/backend
@@ -229,3 +228,54 @@ jobs:
           npm install -g pm2
           pm2 stop all
           pm2 start /var/www/backend/app.js --name backend'
+
+  deploy_frontEnd:
+    needs:
+      - test_frontend
+      - test_node
+
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+
+      - name: Add SSH key
+        uses: webfactory/ssh-agent@v0.5.4
+        with:
+          ssh-private-key: ${{ secrets.EC2_KEY }}
+
+      - name: Install dependecies of frontend
+        working-directory: ./front
+        run: npm i
+
+      - name: Run Build of  frontend
+        working-directory: ./front
+        run: npm run build
+
+      - name: Copy Files to EC2
+        run: |
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+            if [ -d "/var/www/frontend" ];
+            then
+            rm -rf /var/www/frontend
+            fi
+            mkdir /var/www/frontend'
+          rsync -avz -e "ssh" ./front/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/frontend
+          rsync -avz -e "ssh" ./front/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/frontend/package.json
+          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+          export NVM_DIR="$HOME/.nvm"
+          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
+          echo "nvm.sh not found"
+          exit 1
+          }
+
+          nvm use --lts
+
+          cd /var/www/frontend
+          npm i --production
+          sudo  rm -rf ./**/*/*.map'
